version: "3.7"
services:
  api:
    build:
      context: .
      target: build
    volumes:
      - ./:/app
      - /app/node_modules
      - /host/path/to/files:/app/files
    depends_on:
      - cache
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    environment:
      - FILE_BASE_PATH=/app/files
    command: npm run dev

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    networks:
      - mynetwork
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

networks:
  mynetwork:
    driver: bridge

volumes:
  cache:
    driver: local