version: "3.7"
services:
  runner:
    container_name: runner-1
    build:
      context: .
      target: production
    volumes:
      - ./:/app
      - /app/node_modules
      - /host/path/to/files:/app/files
    tty: true
    stdin_open: true
    depends_on:
      - cache
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    environment:
      - FILE_BASE_PATH=/app/files
      - TERM=xterm
    command: node dist/index.js

  queue_worker:
      container_name: queue_worker-1
      build:
        context: .
        target: production
      volumes:
        - ./:/app
        - /app/node_modules
        - /host/path/to/files:/app/files
      depends_on:
        - cache
      networks:
        - mynetwork
      command: node dist/Service.QueueWorker/index.js

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    networks:
      - mynetwork
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

networks:
  mynetwork:
    driver: bridge

volumes:
  cache:
    driver: local